### ISSUE TITLE
Gender and age detection model not found

### ISSUE THREAD

**Issue by numblr** [tae898/face#1]
The app terminates with the following error:
```
Model file is not found. Downloading.
Downloading /Users/tkb/.insightface/models/genderage_v1.zip from http://insightface.ai/files/models/genderage_v1.zip...
2021-07-29 10:51:57.224 DEBUG connectionpool - _new_conn: Starting new HTTP connection (1): insightface.ai:80
2021-07-29 10:51:58.607 DEBUG connectionpool - _make_request: http://insightface.ai:80 "GET /files/models/genderage_v1.zip HTTP/1.1" 404 5232
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    ga_name='genderage_v1')
  File "/Users/tkb/automatic/workspaces/robo/face/face/insightface/venv/lib/python3.7/site-packages/insightface/app/face_analysis.py", line 32, in __init__
    self.ga_model = model_zoo.get_model(ga_name)
  File "/Users/tkb/automatic/workspaces/robo/face/face/insightface/venv/lib/python3.7/site-packages/insightface/model_zoo/model_zoo.py", line 43, in get_model
    net = _models[name](**kwargs)
  File "/Users/tkb/automatic/workspaces/robo/face/face/insightface/venv/lib/python3.7/site-packages/insightface/model_zoo/face_genderage.py", line 73, in genderage_v1
    return get_genderage("v1", download=True, **kwargs)
  File "/Users/tkb/automatic/workspaces/robo/face/face/insightface/venv/lib/python3.7/site-packages/insightface/model_zoo/face_genderage.py", line 68, in get_genderage
    _file = get_model_file("genderage_%s" % name, root=root)
  File "/Users/tkb/automatic/workspaces/robo/face/face/insightface/venv/lib/python3.7/site-packages/insightface/model_zoo/model_store.py", line 92, in get_model_file
    overwrite=True)
  File "/Users/tkb/automatic/workspaces/robo/face/face/insightface/venv/lib/python3.7/site-packages/insightface/utils/download.py", line 73, in download
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url http://insightface.ai/files/models/genderage_v1.zip
```

**Comment by tae898** [comment]
The quality of the gender and age detection model provided by insightface was too poor. I removed them.
